version: '3.3'

volumes:
  db-data:
    driver: local

services:
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'backend'
      MYSQL_USER: 'backend'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  cache:
    image: redis:alpine
    command: ["--notify-keyspace-events", "Egx"]
